version: '3'

services:
  device-dual-camera:
    image: registry.jiangxingai.com:5000/base/rkmpp-gstreamer:arm64v8-cpu-1.0.0
    container_name: edgex-device-dual-camera
    hostname: edgex-device-dual-camera
    restart: always
    command: -e --gst-debug-level=3 v4l2src device=/dev/video0 ! image/jpeg,width=1920,height=1080,framerate=30/1 ! jpegdec ! tee name=t t. ! queue flush-on-eos=true ! jpegenc ! multifilesink location=/data/tmpfs/camera/capture.jpg max-files=1 post-messages=true t. ! queue ! videoconvert ! queue ! videoscale ! video/x-raw,width=1280,height=720 ! queue ! mpph264enc vbr=false bitrate=\"800000\" filerate=false ! queue ! h264parse ! tee name=v v. ! queue ! flvmux streamable=true ! rtmpsink sync=false location=rtmp://172.17.0.1/live/camera0
    privileged: true
    volumes:
      - /tmp:/tmp
      - /data/tmpfs:/data/tmpfs
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video2:/dev/video2"

networks:
  default:
    external:
      name: edgex
